version: '3.8'

services:
  postgres-test:
    image: postgres:13
    container_name: elta-postgres-test
    ports:
      - "5433:5432"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DB: elta_test
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data: 